# Generated by Django 4.1.7 on 2023-02-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_health', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='notes',
        ),
        migrations.AddField(
            model_name='patient',
            name='notes',
            field=models.ManyToManyField(to='platform_health.note'),
        ),
    ]
