# Generated by Django 4.1.7 on 2023-03-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_health', '0002_alter_person_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
