# Generated by Django 4.1.7 on 2023-02-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_health', '0002_alter_doctor_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persondata',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.CharField(default='', max_length=19, unique=True),
            preserve_default=False,
        ),
    ]
