# Generated by Django 4.1.7 on 2023-02-18 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0001_initial'),
        ('platform_health', '0003_person_remove_patient_notes_remove_patient_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='beats',
        ),
        migrations.RemoveField(
            model_name='person',
            name='height',
        ),
        migrations.RemoveField(
            model_name='person',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='person',
            name='weight',
        ),
        migrations.AlterField(
            model_name='person',
            name='level',
            field=models.CharField(choices=[('A', 'Admin'), ('D', 'Doctor'), ('P', 'Patients')], default='P', max_length=1),
        ),
        migrations.CreateModel(
            name='PersonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('phone_number', models.CharField(max_length=19, unique=True)),
                ('beats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arduino.beats')),
                ('notes', models.ManyToManyField(to='platform_health.note')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_health.person')),
            ],
        ),
    ]
