# Generated by Django 4.1.7 on 2023-02-22 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_health', '0004_alter_doctor_person_alter_note_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondata',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_health.doctor'),
        ),
    ]
