# Generated by Django 4.1.7 on 2023-02-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_health', '0005_remove_persondata_beats_alter_persondata_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondata',
            name='height',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='weight',
            field=models.FloatField(blank=True),
        ),
    ]
