# Generated by Django 4.1.7 on 2023-02-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_health', '0007_alter_persondata_height_alter_persondata_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondata',
            name='height',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='weight',
            field=models.FloatField(blank=True),
        ),
    ]
