# Generated by Django 4.1.7 on 2023-02-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0003_rename_beats_heartratedata_beat_and_more'),
        ('platform_health', '0009_alter_persondata_height_alter_persondata_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondata',
            name='beats',
            field=models.ManyToManyField(blank=True, related_name='beats', to='arduino.heartratedata'),
        ),
    ]
