# Generated by Django 4.1.7 on 2023-02-21 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0002_rename_beats_heartratedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heartratedata',
            old_name='beats',
            new_name='beat',
        ),
        migrations.RemoveField(
            model_name='heartratedata',
            name='user',
        ),
    ]
